#!/usr/bin/env python3
"""
Nightly Memory Mining Script

Generates conservative candidate files for memory and skill updates
by scanning daily operational records. Does NOT directly edit
curated memory files.

Usage:
    python3 nightly-memory-mine.py                    # mine today
    python3 nightly-memory-mine.py --date 2026-04-01  # mine specific date
    python3 nightly-memory-mine.py --dry-run          # preview without writing

Outputs:
    memory/candidates/YYYY-MM-DD-memory-candidates.md
    memory/skills/candidates/YYYY-MM-DD-skill-candidates.md
"""

import argparse
from datetime import datetime
from pathlib import Path
import re

# ============================================================
# CONFIGURATION - Edit these paths for your environment
# ============================================================

# Primary workspace containing memory/, coordination/, etc.
WORKSPACE = Path('/Users/mirabot/.openclaw/workspace')

# Secondary agent workspace (for outbox integration, optional)
# Set to None if not using multi-agent delegation
AGENT_WORKSPACE = Path('/Users/mirabot/.openclaw/workspace-patchbay')

# ============================================================


def read_text(path: Path) -> str:
    """Safely read a file, returning empty string on error."""
    try:
        return path.read_text()
    except Exception:
        return ''


def summarize_bullets(text: str, limit: int = 8) -> list[str]:
    """Extract meaningful lines from text, up to limit."""
    lines = []
    for line in text.splitlines():
        s = line.strip()
        if not s:
            continue
        # Skip headers and metadata lines
        if s.startswith(('## ', '# ', 'id:', 'from:', 'to:', 'status:', 'created_at:')):
            continue
        # Extract bullet content or substantial lines
        if s.startswith(('- ', '* ')):
            lines.append(s[2:].strip())
        elif len(s) > 40:
            lines.append(s)
        if len(lines) >= limit:
            break
    return lines[:limit]


def task_summaries(task_dir: Path, limit: int = 6) -> list[tuple[str, str]]:
    """Extract (task_id, objective) pairs from task files."""
    out = []
    if not task_dir.exists():
        return out
    for path in sorted(task_dir.glob('*.md'))[:limit]:
        txt = read_text(path)
        # Extract task ID
        m = re.search(r'^id:\s*(.+)$', txt, re.M)
        task_id = m.group(1).strip() if m else path.stem
        # Extract objective
        objective = ''
        mo = re.search(r'## Objective\n(.+?)(\n## |\Z)', txt, re.S)
        if mo:
            objective = ' '.join(line.strip() for line in mo.group(1).strip().splitlines())
        out.append((task_id, objective or path.name))
    return out


def outbox_summaries(limit: int = 5) -> list[tuple[str, str, list[str]]]:
    """Extract (filename, title, bullets) from agent outbox."""
    out = []
    if AGENT_WORKSPACE is None:
        return out
    outbox = AGENT_WORKSPACE / 'outbox'
    if not outbox.exists():
        return out
    for path in sorted(outbox.glob('*.md'))[-limit:]:
        txt = read_text(path)
        # Extract title from first heading
        title = ''
        mt = re.search(r'^#\s+(.+)$', txt, re.M)
        if mt:
            title = mt.group(1).strip()
        out.append((path.name, title or path.name, summarize_bullets(txt, 4)))
    return out


def existing_skill_titles() -> list[str]:
    """Get lowercase titles of existing skill docs."""
    skill_dir = WORKSPACE / 'memory' / 'skills'
    titles = []
    if not skill_dir.exists():
        return titles
    for path in skill_dir.glob('*.md'):
        if path.parent.name == 'candidates':
            continue
        txt = read_text(path)
        mt = re.search(r'^#\s+(.+)$', txt, re.M)
        if mt:
            titles.append(mt.group(1).strip().lower())
    return titles


def generate_memory_candidates(day: str, daily_text: str, done_tasks: list, outbox: list) -> list[str]:
    """Generate memory candidate file content."""
    lines = [
        f'# Memory Candidates - {day}',
        '',
        'Generated by nightly mining. Review and promote as appropriate.',
        '',
        '## Candidate observations',
        ''
    ]

    if daily_text:
        for bullet in summarize_bullets(daily_text, 6):
            lines.append(f'- Candidate: {bullet}')
            lines.append('  - Suggested action: review for promotion to long-term or project memory')
    else:
        lines.append('- No daily memory file found for this date.')

    if done_tasks:
        lines.extend(['', '## Coordination outcomes', ''])
        for task_id, objective in done_tasks[:5]:
            lines.append(f'- Completed task: `{task_id}`')
            lines.append(f'  - Outcome hint: {objective}')
            lines.append('  - Suggested action: check if outcome belongs in project or long-term memory')

    if outbox:
        lines.extend(['', '## Agent outbox highlights', ''])
        for name, title, bullets in outbox:
            lines.append(f'- Result file: `{name}` — {title}')
            for b in bullets[:3]:
                lines.append(f'  - Evidence: {b}')

    return lines


def generate_skill_candidates(day: str, done_tasks: list, outbox: list, skill_titles: list) -> list[str]:
    """Generate skill candidate file content."""
    lines = [
        f'# Skill Candidates - {day}',
        '',
        'Generated by nightly mining. Review for new skills or updates to existing ones.',
        '',
        '## Candidate skills / workflow updates',
        ''
    ]

    seeded_candidates = []

    # Check for delegation-related completions
    if any('patchbay' in (tid.lower() + ' ' + obj.lower()) for tid, obj in done_tasks):
        seeded_candidates.append({
            'title': 'Delegating project packaging and repo publication to agents',
            'action': 'new_or_merge',
            'why': 'A successful end-to-end delegation workflow exists using project bundles, task briefs, and coordination bus.',
            'evidence': 'coordination task completion + agent outbox result'
        })

    # Check for memory-related work
    if outbox and any('memory' in (name.lower() + title.lower()) for name, title, _ in outbox):
        seeded_candidates.append({
            'title': 'Use candidate-first memory improvement rather than direct autonomous rewriting',
            'action': 'new_or_merge',
            'why': 'Current design intentionally separates nightly mining from direct promotion into curated memory.',
            'evidence': 'memory-improvement system architecture and cron plan'
        })

    if not seeded_candidates:
        lines.append('- No skill candidates identified for this date.')
        lines.append('  - Note: Add heuristics to detect reusable patterns from your workflows.')
        return lines

    for cand in seeded_candidates:
        lower_title = cand['title'].lower()
        maybe_merge = any(lower_title in t or t in lower_title for t in skill_titles)
        lines.append(f'- Title: {cand["title"]}')
        lines.append(f'  - Suggested action: {"merge/update existing skill" if maybe_merge else cand["action"]}')
        lines.append(f'  - Why: {cand["why"]}')
        lines.append(f'  - Evidence: {cand["evidence"]}')
        lines.append('')

    return lines


def ensure_directories():
    """Create candidate directories if they don't exist."""
    (WORKSPACE / 'memory' / 'candidates').mkdir(parents=True, exist_ok=True)
    (WORKSPACE / 'memory' / 'skills' / 'candidates').mkdir(parents=True, exist_ok=True)


def main():
    parser = argparse.ArgumentParser(
        description='Generate memory and skill candidates from daily operational records.'
    )
    parser.add_argument(
        '--date',
        help='Date in YYYY-MM-DD format (defaults to today)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Preview output without writing files'
    )
    args = parser.parse_args()

    day = args.date or datetime.now().strftime('%Y-%m-%d')

    # Gather inputs
    daily_file = WORKSPACE / 'memory' / f'{day}.md'
    daily_text = read_text(daily_file)
    done_tasks = task_summaries(WORKSPACE / 'coordination' / 'tasks' / 'done')
    failed_tasks = task_summaries(WORKSPACE / 'coordination' / 'tasks' / 'failed')
    outbox = outbox_summaries()
    skill_titles = existing_skill_titles()

    # Generate candidates
    memory_lines = generate_memory_candidates(day, daily_text, done_tasks, outbox)
    skill_lines = generate_skill_candidates(day, done_tasks, outbox, skill_titles)

    if args.dry_run:
        print('=== MEMORY CANDIDATES ===')
        print('\n'.join(memory_lines))
        print('\n=== SKILL CANDIDATES ===')
        print('\n'.join(skill_lines))
        return

    # Write outputs
    ensure_directories()
    mem_out = WORKSPACE / 'memory' / 'candidates' / f'{day}-memory-candidates.md'
    skill_out = WORKSPACE / 'memory' / 'skills' / 'candidates' / f'{day}-skill-candidates.md'

    mem_out.write_text('\n'.join(memory_lines).rstrip() + '\n')
    skill_out.write_text('\n'.join(skill_lines).rstrip() + '\n')

    print(f'Wrote {mem_out}')
    print(f'Wrote {skill_out}')


if __name__ == '__main__':
    main()
